apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost
spec:
  backend:
    serviceName: ghost
    servicePort: 80
  tls:
    - secretName: "ghost-tls"
      hosts:
        - "*.example.com"
